Twitter.App/Controllers/TweetsController.cs
namespace Twitter.App.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using Twitter.Data.UnitOfWork;

    using Microsoft.AspNet.Identity;

    using Twitter.App.Models.BindingModels;
    using Twitter.App.Models.ViewModels;
    using Twitter.Models;

    [Authorize]
    [RoutePrefix("tweets")]
    public class TweetsController : BaseController
    {
        public TweetsController()
            : base(new TwitterData())
        {
        }

        [HttpGet]
        [Route("create")]
        public ActionResult NewTweetForm()
        {
            return this.PartialView("_NewTweetModal");
        }

        [HttpPost]
        [Route("add")]
        public ActionResult InsertTweet(CreateTweetBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.Response.StatusCode = 400;
                return this.Json(this.ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage));
            }

            var loggedUserId = this.User.Identity.GetUserId();
            var loggedUserUsername = this.User.Identity.GetUserName();

            var tweet = new Tweet { Text = model.Text, AuthorId = loggedUserId, DatePosted = DateTime.Now };

            this.Data.Tweets.Add(tweet);

            this.Data.SaveChanges();

            return this.PartialView(
                "_Tweet",
                new TweetViewModel
                    {
                        Id = tweet.Id,
                        Author = loggedUserUsername,
                        DatePosted = tweet.DatePosted,
                        RetweetsCount = tweet.Retweets.Count,
                        RepliesCount = tweet.Replies.Count,
                        Text = tweet.Text,
                        UsersFavouriteCount = tweet.UsersFavourite.Count
                    });
        }

        public int Favourite(int tweetId)
        {
            var loggedUserId = this.User.Identity.GetUserId();
            var tweet = this.Data.Tweets.Find(tweetId);

            this.Data.Users.Find(loggedUserId).FavouriteTweets.Add(tweet);

            this.Data.SaveChanges();

            return tweet.UsersFavourite.Count();
        }
    }
}

Twitter.App/Controllers/UsersController.cs
namespace Twitter.App.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using Microsoft.Ajax.Utilities;

    using Twitter.App.Models.ViewModels;
    using Twitter.Data.UnitOfWork;

    [RoutePrefix("users")]
    public class UsersController : BaseController
    {
        public UsersController()
            : base(new TwitterData())
        {
        }

        [Route("search")]
        public ActionResult SearchUser(string searchTerm)
        {
            if (searchTerm.IsNullOrWhiteSpace())
            {
                return this.HttpNotFound();
            }

            var users =
                this.Data.Users.All()
                    .Where(u => u.UserName.Contains(searchTerm))
                    .Select(u => new UserViewModel { Username = u.UserName, Email = u.Email });

            if (!users.Any())
            {
                return this.HttpNotFound();
            }
            
            return this.View(users);
        }
    }
}

Twitter.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Twitter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Twitter", "Index", "Home", new { area = string.Empty }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                @if (Request.IsAuthenticated)
                {
                    <li>
                        @Ajax.ActionLink("New Tweet", "NewTweetForm", "Tweets",
                        new AjaxOptions
                        {
                            UpdateTargetId = "new-tweet", // <-- DOM element ID to update
                            InsertionMode = InsertionMode.Replace, // <-- Replace the content of DOM element
                            HttpMethod = "GET", // <-- HTTP method,
                            OnSuccess = "app.showNewTweetModal"
                        })
                    </li>
                }

                @using (Html.BeginForm("SearchUser", "Users", FormMethod.Post, new { @class = "navbar-form navbar-left" }))
                {
                    <li class="form-group">
                        <input type="text" class="form-control" name="searchTerm" placeholder="Search">
                    </li>
                    <button type="submit" class="btn btn-default">Submit</button>
                }
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    <div id="new-tweet"></div>
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Twitter</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>